sonar.projectKey=FinditItems_Findit_Backend_v1
sonar.organization=findititems
sonar.host.url=https://sonarcloud.io

sonar.sources=services
sonar.tests=services
sonar.test.inclusions=**/*.test.ts,**/*.spec.ts
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/*.test.ts,**/*.spec.ts
